### ISSUE TITLE
Ugene not installing all files in $PREFIX

### ISSUE THREAD

**Issue by staalmannen** [ugeneunipro/ugene#683] opened 2021-12-27 05:15 UTC
only the following files installed in the PREFIX:
`LICENSE.txt  LICENSE.3rd_party.txt  application-x-ugene.xml  application-x-ugene-ext.png  data  plugins  transl_ru.qm  transl_tr.qm  ugene  ugene.desktop  ugene.png  ugene.xpm  ugene.1.gz`

https://github.com/BioArchLinux/Packages/issues/12

In the last working build (PKGBUILD not changed), the following files were installed in the PREFIX:
`LICENSE.txt              application-x-ugene-ext.png  libU2Algorithm.so  libU2Formats.so  libU2Private.so  libU2View.so    libsamtools.a  plugins_checker  ugene          ugene.xpm  ugeneui
LICENSE.3rd_party.txt    data                         libU2Core.so       libU2Gui.so      libU2Script.so   libbreakpad.so  libugenedb.so  transl_ru.qm     ugene.desktop  ugenecl    ugene.1.gz
application-x-ugene.xml  libQSpec.so                  libU2Designer.so   libU2Lang.so     libU2Test.so     libqscore.a     plugins        transl_tr.qm     ugene.png      ugenem`

**Comment by staalmannen** [comment] 2021-12-27 05:23
Is there a different mechanism for installing different files? I will have to investigate it, but it might have to do with different manners of building / packaging (manual vs automatic). If that is the case, is there anything different between the files above in terms of how they get installed to PREFIX?

**Comment by yalgaer** [comment] 2021-12-30 03:32
According to the build [file](https://github.com/ugeneunipro/ugene/blob/aea00019c64ea65bbe74844a7b47d4bc19801038/ugene.pri#L50) the whole release build dir must be included. 

Let me check it locally and I will provide more details if this is a bug or not


BTW:  this is not the official way of building UGENE. We never test this build target. 

Is it possible to download our pre-built/tested source/binary packages from [here](https://github.com/ugeneunipro/ugene/releases) and include them into the distribution?

**Comment by yalgaer** [comment] 2021-12-30 16:04
Please check if the fix works for you.

I some issues still remaining: the 'make install' copies non-release files into the bundle: test plugins, some static libraries. 
We have a 'release-bundle.txt' file that has a complete list of what should go into the release. 

May an extra cleanup script that will remove all files not in the 'release-bundle.txt' is needed here too.

**Comment by staalmannen** [comment] 2022-01-02 04:17
> According to the build [file](https://github.com/ugeneunipro/ugene/blob/aea00019c64ea65bbe74844a7b47d4bc19801038/ugene.pri#L50) the whole release build dir must be included.
> 
> Let me check it locally and I will provide more details if this is a bug or not
> 
> BTW: this is not the official way of building UGENE. We never test this build target.
> 
> Is it possible to download our pre-built/tested source/binary packages from [here](https://github.com/ugeneunipro/ugene/releases) and include them into the distribution?

We can do the binary release, but there are major advantages of doing the source package. The binary package is almost 1 GiB and has its own Qt libraries etc, which means that it does not follow system theming. The same package built from source is about 100 MiB (external tools in separate packages).

Thanks for the fixes. I will try to test it as soon as possible.

**Comment by StefanBruens** [comment] 2022-02-21 00:57
Cherry-picked the change, but it does not fix the problem.

What happens here is the result of qmake depends on the build. The glob for ugene_build_dir.files depends on the build artifacts.

So on the first run, ugenecl/ugeneui/ugenem and the libs are not found by the globs and omitted by `make install`.

When you run qmake again, and then `make; make install`, the executables and libs are installed. You can verify this when you diff the Makefile after the first and second qmake invocation.

BTW, also the static libraries are installed.

**Comment by StefanBruens** [comment] 2022-12-30 10:36
@yalgaer - can you please reopen this, as it is apparently not fixed (also in ugene 45 and master).

**Comment by yalgaer** [comment] 2023-01-03 18:37
@StefanBruens why do you need `make install` at all? 
This is an old `artifact` target we do not support/test at all.

I think the better option could be providing a separate script (like we have in etc/linux/build.sh) that will bundle the build artifacts into a separate 'package' folder. If you want to put libs/data differently it should be your own script, UGENE patches, tests.

The current 'build.sh' script should do the job for you, we only need to make the inclusion of Qt libs optional.

**Comment by StefanBruens** [comment] 2023-01-03 19:26
> @StefanBruens why do you need `make install` at all? This is an old `artifact` target we do not support/test at all.
> 
> I think the better option could be providing a separate script (like we have in etc/linux/build.sh) that will bundle the build artifacts into a separate 'package' folder. If you want to put libs/data differently it should be your own script, UGENE patches, tests.
> 
> The current 'build.sh' script should do the job for you, we only need to make the inclusion of Qt libs optional.

Because `make install` is just somewhat broken, while everything `build.sh` does is way off from any standard packaging scheme.

1. Libs should go into `/usr/lib64/`, icons into `/usr/share/icons/hicolor/...`, and so on.
2. Installation should honor $DESTDIR as a staging directory
3. ... and quite some more

CMake (and qmake) already handle all this, and everytime a project tries to do this themselves (ugene is not alone here) things break in various ways.

**Comment by yalgaer** [comment] 2023-01-04 00:40
Hi Stefan, we tried to support multiple Linux distributions for many years some time ago. 

A lot of Unix-like OSes have their own filesystem layouts, different versions of Qt and other libraries installed. All that zoo lead to different issues when users got a non-tested product at the end.

We ended up using a simple 'unpack-and-use-everywhere' tar.gz file that includes everything (Qt, custom-biult sqlite, etc...).

We test this locked bundle before each release and all user needs is to unpack it (tar xf ugene.tar.gz).

Support of any specific Linux distribution with an alternative `make-install` or packager will require extra resources (test, reply to issues) we do not have today.

But I will be glad to review & approve any patch that will improve existing `make install` subsystem.

**Comment by yalgaer** [comment] 2023-01-27 06:43
Closing as not active. Please re-open with a patch

**Closed as completed by yalgaer** 2023-01-27 06:43 UTC

**Comment by StefanBruens** [comment] 2023-01-28 02:38
When using CMake, all distribution differences are already covered.

Extra work is only caused by doing everything manually, instead of generally available and tested tools.

Noteworthy CPPCon talk (not from a Linux distribution, but a Microsoft employee): https://youtu.be/sBP17HQAQjk?t=198
