### ISSUE TITLE
ugene-37.0: Translation not found: transl_cs

### ISSUE THREAD

**Issue by mmokrejs** [ugeneunipro/ugene#294] opened 2021-03-18 18:32 UTC
Hi,
  when starting the cmdline utilities I get unclear error:

```
ugene local-blast+ --in=input.fa --dbpath=. --dbname=mydb --out=output.gb
Translation not found: transl_cs
```

I figured out there is just English and Russian localization but I guess many people will not realize. Make the tool revert to English by default, please.

`LANG=en ugene --help=local-blast+`

**Comment by DmitriiSukhomlinov** [comment] 2021-03-19 13:32
Hello,

This is not bug, but a feature. When you start UGENE command-line, it checks translation files in the following order:

1. The argument "lang". You may run UGENE with the additional argument `--lang=en` or  `--lang=ru` (only English or Russian languages are supported).
2.  Read the language setting from the ".ini" file if it's bee saved already.
3. Get your locale language settings. As far as you have the "cs" setting, but this language isn't presented, `Translation not found: transl_cs` has been texted to the log.
4. Default English translation.

I suggest you use English language in command-line interface.

**Comment by mmokrejs** [comment] 2021-03-20 22:11
Hi,
  but the message is actually an error, not a warning. And what I propose is that the tools automatically switches to english, if the input locale is not supported. I am not asking for translation in czech, of course. Other tools do the same. And, it is handy if messages printed on STDERR are prefixed with "Warning: " or  "Error: ", then it is clear why an application exit with a non-zero status or just continued.

**Comment by yalgaer** [comment] 2021-03-24 01:43
Hi Martin,

I added this problem into our local dev-tracker here: https://ugene.dev/tracker/browse/UGENE-7140
We will address it in the upcoming release (end of May/June).

I will update this issue with details too once the problem is fixed.

**Comment by yalgaer** [comment] 2021-03-28 05:38
The fix was merged to the master and will be released as a part of v39
https://github.com/ugeneunipro/ugene/pull/307

**Closed as completed by yalgaer** 2021-03-28 05:38 UTC

**Comment by mmokrejs** [comment] 2021-03-28 06:06
Does the program revert to English if a translation file is not found? Seems like that in https://github.com/ugeneunipro/ugene/commit/52469c6258ec00b891010bed3c81d1c47ebb31dd were you keep only Russian as a translation file and English is the default.

Also, you may expect people do not have a specific language so you may also observe LANG=C and LC_ALL=C . https://unix.stackexchange.com/questions/576701/what-is-the-difference-between-lang-c-and-lc-all-c

Seems you do not like `Warning:` and `Error:` prefixes in strings being output to `STDERR`, but as you wish.

Thank you for your efforts.
